name: CI/CD-HUGO-Build-Forward
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.102.3"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_TOKEN }}
          external_repository: progami/Cloud-Resume-Challenge-AWS
          publish_dir: ./public
          keep_files: true
          user_name: progami # secret this --> TODO
          user_email: jarraramjad@gmail.com # secret this --> TODO
          publish_branch: main
          destination_dir: resume-site
        #   cname: example.com